### ISSUE TITLE
How to handle the pull requests with many modifications?

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#49]
So, after sending the Pull Requests, many alterations were recommended, and it was suggested to even alter the name of the functions. I'm new to Open Source contributing. What is the proper way to handle such cases? Should I cancel my pull request and send another one with the changes made?

**Comment by davibarreira** [comment]
By the way, once we incorporate the new functions and change the name of the functions (e.g. `emd` to `optimal_transport_plan` or `otplan`), we should probably release a new version.

**Comment by devmotion** [comment]
Usually one just iterates until everyone is happy :slightly_smiling_face: When one reviews the PR on Github, then only the diff of the latest changes is shown, so it does not matter how many commits are contained in the PR. One can then "Squash and merge" at the end (not regular merge) to polish the git history and avoid that all the intermediate commits end up in the master branch.

**Comment by devmotion** [comment]
> By the way, once we incorporate the new functions and change the name of the functions (e.g. emd to optimal_transport_plan or otplan), we should probably release a new version.

I'm a big fan of [ColPrac](https://colprac.sciml.ai/) (which we could/should adopt as well) and making a release after every PR that affects the package - either it's a bug fix or a new feature, and in both cases users have a strong interest in being able to use the new implementation as quickly as possible.

On a side note, I think we should deprecate `emd` etc. first in the next (non-breaking!) release to give users the opportunity and time to update their code and removing the deprecations. Also it makes dependency management easier since downstream packages are able to use the new features without having to adjust the compat bounds for OptimalTransport.

**Comment by devmotion** [comment]
And coming back to the initial post: usually it's best to limit the number of changes in each PR from the start. Large PRs with many changes are usually difficult to get right, difficult to review, and therefore take more time until they are approved and merged. So I think, in general, it is better to open multiple small PRs one after another instead of a large one with many changes.

**Comment by davibarreira** [comment]
Just to gain some perspective. Would you say that PR's, such as the last two ones I sent, are Large?

**Comment by devmotion** [comment]
I guess the 1D PR could have been split into a PR for the discrete case and the continuous one. I think it is good to have both the implementation for the transport map and cost in the same PR though since they belong together. Additionally, I guess it would have been better to add the longer example in a second PR afterwards since I think examples can take more time to write and review (and to not use a Jupyter notebook but a Literate script as [on the master branch](https://github.com/zsteve/OptimalTransport.jl/blob/master/examples/basic/script.jl) since this would make maintenance and reviews easier :wink:).

**Comment by zsteve** [comment]
Hi both,
I am also not too familiar with collaborative projects but keen to learn. So I defer to @devmotion's judgment here. ColPrac as a standard sounds great, I will take a look to familiarise myself with it.
