### ISSUE TITLE
Convention about using greek letters/unicode or ASCII variable naming

### ISSUE THREAD

**Issue by zsteve** [JuliaOptimalTransport/OptimalTransport.jl#54]
Currently most of the code uses ASCII variable names (e.g. `mu`, `nu`). The benefit here is that it can be easier to deal with. However, I was thinking perhaps it it is more idiomatic Julia to use Greek/Unicode (e.g. `μ`) for the internals? In any case, we should decide on a convention since currently both ASCII and symbols are used.

**Comment by devmotion** [comment]
Yes, I think it would be good to be a bit more consistent. I try to avoid Unicode characters in the official API since it might break stuff for some users, but I think it is fine and can be more idiomatic to use Unicode characters for internal variables where it's appropriate.

**Comment by davibarreira** [comment]
@devmotion , can you exemplify? It's not clear to me what you are proposing.

**Comment by devmotion** [comment]
I'd say it's OK to use Unicode characters as internal variables (if they are not too weird, one should not make it unnecessarily difficult for users to contribute to the package) but I think one should avoid to use Unicode characters in e.g. names and keyword arguments of exported functions if there is no ASCII alias.

**Comment by davibarreira** [comment]
I agree with this (although I do love using unicode on my functions). I'll update my implementations from $\mu$ to mu, and change all `c` to `C`.

**Comment by devmotion** [comment]
I think there might be some misunderstanding here. I think it's fine to use unicode-mu for positional  arguments (users do not have to type mu) and as name for an internal variable (since it's a quite standard unicode character). For keyword arguments, however, I think it would be better not to enforce unicode characters since this might be problematic for users (they have to type the name!). However, IMO one could still use them IF one provides an ASCII alternative: e.g., one could define `f(args...; epsilon=0.01, "\varepsilon"=epsilon)`, then users can use the "nice" Unicode name but could still use the ASCII alternative if this is problematic for them.

I am not sure why you would want to change `c` to `C`?
